main: me.tecspace.skworldedit.SkWorldEdit
name: SkWorldEdit
version: '${version}'
description: "A Skript addon letting you interact with WorldEdit"
author: tecspace
api-version: '${apiversion}'
dependencies:
  server:
    Skript:
      load: BEFORE
      required: true
    WorldEdit:
      load: BEFORE
      required: true